### ISSUE TITLE
They false ban

### ISSUE THREAD

**Issue by DusterMinecraft** [GlobalCraftMC/GlobalCraft-Webpage#1]
They banned me on hypixel for using xray. yeah i was using xray but they didnt have any proof as my tunnels werent xray tunnels
![Screenshot (451)](https://user-images.githubusercontent.com/100651649/156086213-887cce80-c98d-423d-9ac7-e69505133908.png)

**Comment by GlobalCraftMC** [comment]
What does this have anything to do with our server?
